name: 'Test'
description: 'Test ain-js using local blockchain'
inputs:
  environment:
    description: 'Environment to test'
    required: true
    default: 'prod'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.environment }}
