name: PR Test
on:
  pull_request:
    branches: [ develop ]
    types: [ opened, closed ]

jobs:
  run_test_on_testnet:
    if: ${{ !(github.event.action == 'closed') || (github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        uses: ./
        id: test-pipeline
        with:
          environment: 'dev'

  execute_on_failure:
    needs: [ run_test_on_testnet ]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Get error log
        run: |
          echo "ERROR_LOG=$(gh run view ${{ github.run_id }} --log | grep error)" >> $GITHUB_ENV
      - name: Notify error to slack
        # send notify slack only when pr is merged
        if: ${{ github.event.action == 'closed' }}
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Test failed for [PR#${{ github.event.number }}](${{ github.event.pull_request.html_url }})",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":rotating_light:TEST FAILED",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Test failed for [PR#${{ github.event.number }}](${{ github.event.pull_request.html_url }})"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Error log*\n${{ env.ERROR_LOG }}\nCheck full logs in ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
