name: PR Test
on:
  pull_request:
    branches: [ master ]

jobs:
  run_test_on_testnet:
    if: ${{ !startsWith(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run test
        uses: ./
        id: test-pipeline
        with:
          environment: 'dev'
  run_test_on_mainnet:
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run test
        uses: ./
        id: test-pipeline

