name: Test Pipeline for opened PR
on:
  pull_request:
    branches: [ master, develop ] #put your branches which you want to execute test pipeline
    types: [ opened, ready_for_review ]
concurrency: 
      group: ${{ github.event.pull_request.number }}
      cancel-in-progress: true
jobs:
  run_test_on_testnet:
    if: ${{ github.base_ref == 'develop' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        uses: ./
        id: test-pipeline
        with:
          environment: 'dev'
  run_test_on_mainnet:
    if: ${{ github.base_ref == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        uses: ./
        id: test-pipeline
