name: Test Pipeline for Merged PR
on:
  pull_request:
    branches: [ master, develop ]
    types: [ closed ]
concurrency: 
      group: ${{ github.event.pull_request.number }}
      cancel-in-progress: true
jobs:
  run_test_on_testnet:
    if: ${{ github.base_ref == 'develop' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        uses: ./
        id: test-pipeline
        with:
          environment: 'dev'
  run_test_on_mainnet:
    if: ${{ github.base_ref == 'master' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        uses: ./
        id: test-pipeline
  publish:
    needs: [ run_test_on_mainnet ]
    if: ${{ startsWith(github.head_ref, 'release/') && (github.base_ref == 'master') && (github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn
      - name: Publish package
        run: |
          yarn build
          yarn publish --access public
          echo "NEW_VERSION=$(npm pkg get version | tr -d '"')" >> $GITHUB_ENV
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - name: Push tag
        run: |
          git tag v${{ env.NEW_VERSION }}
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify package published to slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Ain-js ${{ env.NEW_VERSION }} is published",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Ain-js Release"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Version ${{ env.NEW_VERSION }} is published on <https://www.npmjs.com/package/@ainblockchain/ain-js|npmjs.com>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
